from typing import List
from langchain_core.documents import Document

def prepare_context_for_summary(documents: List[Document]) -> str:
    """
    Prepares a text context from a list of Langchain Document objects for summarization.

    Args:
        documents (List[Document]): A list of Langchain Document objects from PDF.
    Returns:
        str: A single string containing the concatenated text from all documents.
    """

    full_text = full_text = "\n\n--- New Page ---\n\n".join([doc.page_content for doc in documents])

    return full_text

def post_process_summary(raw_summary: str) -> str:
    """
    Applies post-processing to the raw summary generated by the SLM.

    Args:
        raw_summary: The summary text generated by the SLM.
    Returns:
        The final formatted summary.
    """

    processed_summary = raw_summary.strip()
    return processed_summary