name: Frontend CI/CD

on:
  workflow_call:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'frontend/**'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'frontend/**'

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          cache-dependency-path: 'frontend/yarn.lock'
          
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install --frozen-lockfile
        
      - name: Run tests
        working-directory: ./frontend
        run: yarn test
        
      - name: Build
        working-directory: ./frontend
        run: yarn build

  docker-build-frontend:
    needs: test-frontend  # Only build Docker if tests pass
    runs-on: ubuntu-latest做事
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: front-ecosynthesia:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max