name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Mise à jour vers Node.js 20
          cache-dependency-path: 'frontend/yarn.lock'
          
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install --frozen-lockfile
        
      - name: Run tests
        working-directory: ./frontend
        run: yarn test
        
      - name: Build
        working-directory: ./frontend
        run: yarn build